/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

int main(void)
{
    /* Loop forever */
	uint32_t *RCC_ENR = (uint32_t*)(0x40023800 + 0x30);
	*RCC_ENR|=(0x01<<2);

	//Set Port and Pin Mode
	uint32_t *GPIOC_MODER = (uint32_t*)(0x40020800);
	*GPIOC_MODER &= 0xF3FFFFFF;
	*GPIOC_MODER |= (0x01<<26);

	//Set pin 13 of port C to high
	uint32_t *GPIOC_ODR = (uint32_t*)(0x40020800 + 0x14);
	*GPIOC_ODR &= ~(1<<13); //LED is active low
	for(;;);
}
